stages:
  - build
  - deploy
#  - cleanup

build:
#  image: docker:latest
  stage: build
  tags:
    - project_test_230
#  services:
#    - docker:dind
  before_script:
      - echo $env > .env
  script:
    - docker build -t rkp.dthub.uz .
  only:
    - test

deploy:
 stage: deploy
 tags:
    - project_test_230
 script:
    - docker container rm -f rkpdthubuz || true
    - docker run -d -p 7002:80 --restart always -v /etc/localtime:/etc/localtime:ro --name rkpdthubuz rkp.dthub.uz
 only:
    - test

#cleanup:
# stage: cleanup
# tags:
#    - project_test_251
# script:
#    - docker system prune --volumes -f
# only:
#    - test
